quiz.answer_type.*:
  type: config_entity
  label: 'Answer type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    langcode:
      type: string
      label: 'Default language'
